### ISSUE TITLE
get folders from quadlet repo

### ISSUE THREAD

**Issue by geraveoyomama** [ubiquitous-factory/quadit#73]
One of the organisational things I do with my quadlet repo is to place pods and their microservices into subfolders. eg nextcloud has a folder that contains all quadlets to make nextcloud run instead of storing everything in a flat directory.

quadit seems to not be able to pull these subfolders. Is this on purpose?

Thank you for taking your time to read my issue. I am attempting a PR but will probably not get around to it.

Something tangentially related. Is the writing of .container etc exclusive? eg the directory is cleared and only then are new containers loaded so that the config directly reflects the git repo

**Comment by geraveoyomama** [comment]
looking at the way the git config works it seems to not work in the code just yet.

I do believe this is an excellent organisational feature to have.

**Comment by No9** [comment]
Hey - Supporting subfolders is something that wasn't required when I started quadit and it is complicated by the service restart piece a little bit.
Do you have a sample folder structure in mind that I can evaluate?

**Comment by geraveoyomama** [comment]
```
.config/containers/systemd/
├── arr
│   ├── arr.network
│   ├── arr.pod
│   ├── bazarr.container
│   ├── flaresolverr.container
│   ├── gluetun.container
│   ├── lidarr.container
│   ├── prowlarr.container
│   ├── qbittorrent.container
│   ├── radarr.container
│   ├── sabnzbd.container
│   ├── slskd.container
│   ├── sonarr.container
│   └── soularr.container
├── jellyfin
│   ├── jellybot.container
│   ├── jellyfin.container
│   ├── jellyseerr.container
│   ├── jellywind.container
│   └── meilisearch.container
└── mkv
    ├── makemkv.container
    └── makemkv.volume

4 directories, 20 files
```

**Comment by No9** [comment]
Ah now I understand - you would like the target paths respected on the host machine

I still think this comment holds though  
https://github.com/ubiquitous-factory/quadit/blob/main/src/git_manager.rs#L220 
Specifically you have 3 applications `mkv`, `jellyfin` and `arr` and they are likely to change at a different rate so rather than redeploying and restarting all the services it was better to just manage them as seperate application instances as they are likely to change at different rates.

So your config will look something like this:

```
targetConfigs:
- url: https://github.com/geraveoyomama/app
  targetPath: "arr"
  branch: "main"
  schedule: "1/10 * * * * *"
- url: https://github.com/geraveoyomama/app
  targetPath: "jellyfin"
  branch: "main"
  schedule: "1/10 * * * * *"
- url: https://github.com/geraveoyomama/app
  targetPath: "mvk"
  branch: "main"
  schedule: "1/10 * * * * *"
```

And you would like that to be respected in the `.config/containers/systemd/` folder as you posted above.
That makes sense to me from a structure point of view. 

Let me know if I've missed something. If not I'll start that as a feature and I think it should be the default.
